/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 macbook.glb 
Author: Nicholas-3D (https://sketchfab.com/Nicholas01)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-07f012fbd3bb4c37a1b9ed08533ee403
Title: MacBook
*/

import React, { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  // Fix: point to the correct public/models path
  const { nodes, materials } = useGLTF('/models/macbook.glb')
  const group = useRef()

  // Rotate the MacBook slowly around the Y axis
  useFrame((_, delta) => {
    if (group.current) {
      group.current.rotation.y += delta * 0.4 // ~0.4 rad/s (slightly faster)
    }
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Mac_B001_Mac_0.geometry} material={materials.material} position={[0, -0.342, -0.94]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Mac_A001_Mac_0.geometry} material={materials.material} position={[0, -0.342, -0.94]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Mac_B002_Mac_0.geometry} material={materials.material} position={[0, 0.342, 0.94]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Mac_A002_Mac_0.geometry} material={materials.material} position={[0, 0.342, 0.94]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/macbook.glb')
